spring:
  application:
    name: codelib testapp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testapp
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  data:
    rest:
      base-path: /entities
server:
  port: 80
codelib:
  auth:
    enablbe-info: true
    enable-delete: true
    enable-login: true
    enable-register: true
    enable-update: true
  admin:
    enable-sql: true
    enable-dml: true
  settings:
    enable: true